### ISSUE TITLE
ParseError - [!] Array missing ',' in between objects (build setting expansion)

### ISSUE THREAD

**Issue by Ashton-W** [CocoaPods/Nanaimo#23]
We use build setting expansion in our `CODE_SIGN_ENTITLEMENTS`, when using **CocoaPods** we find **Nanaimo** doesn't like it, it works in Xcode. I don't know if it is valid according to 'spec'

### Error

```
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects
     #  -------------------------------------------
     #  				CLANG_ENABLE_CODE_COVERAGE = YES;
     #  				CLANG_ENABLE_MODULES = YES;
11518>  				CODE_SIGN_ENTITLEMENTS = "REDACTED/REDACTED$(ENTITLEMENTS_SUFFIX).entitlements";
        				                          ^
     #  				CODE_SIGN_IDENTITY = "iPhone Developer";
     #  				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
     #  -------------------------------------------

/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:173:in `parse_array'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:133:in `parse_object'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:106:in `parse!'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/xcodeproj-1.4.2/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in `open'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bin/pod:22:in `load'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/bin/pod:22:in `<top (required)>'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/ashton/.rbenv/versions/2.1.3/bin/bundle:22:in `load'
/Users/ashton/.rbenv/versions/2.1.3/bin/bundle:22:in `<main>'
```

**Comment by Ashton-W** [comment]
Looking into a possible issue elsewhere in the project file, will reopen if still valid.

**Comment by segiddins** [comment]
Could you please share the project? Thanks!

**Comment by Ashton-W** [comment]
I can't, but I will try and reproduce it

**Comment by Ashton-W** [comment]
I haven't forgotten, I've just unable to reproduce this. Given that this project wasn't able to be opened by Xcode, it should be OK to just forget about this.
