### ISSUE TITLE
Invalid character "@" in unquoted string

### ISSUE THREAD

**Issue by jpfortin** [CocoaPods/Nanaimo#44]
Hi, first time filling an issue, it seems having a plugin name starting with @ is now a problem. Is it something I'm doing wrong or a change needed in Nanaimo? thanks.

```ruby
post_install do |installer|
  post_install1 installer
  post_install2 installer
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Invalid character "@" in unquoted string
   #  -------------------------------------------
   #                            C8741B0EC1CF4B688BFAA476 /* app */,
   #                    );
193>                    name = @nstudio/nativescript-camera-plus;
                               ^
   #                    sourceTree = "<group>";
   #            };
   #  -------------------------------------------

/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:150:in `parse_string'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:140:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.8.2/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.8.2/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.8.2/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1025:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1024:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1024:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1019:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:96:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by segiddins** [comment]
Can you please share your Xcode project?

**Comment by jpfortin** [comment]
https://github.com/naturalinsight/nativescript-camera-plus

**Comment by jpfortin** [comment]
I'm sorry, this is my client's code. I'll try to find another way for now. I close this. Thanks for offering help.

**Comment by jpfortin** [comment]
Looking at your interactions with others I see that only the pbxproj file could be enough. I tried upgrade/downgrade many gems, without success.

[project.pbxproj.zip.(https://github.com/CocoaPods/Nanaimo/files/3125355/project.pbxproj.zip)

**Comment by segiddins** [comment]
I get the following when trying to open the project in Xcode: `The project ‘issue’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.`

**Comment by jpfortin** [comment]
Thanks for helping. This is a generated NativeScript project and the pod install step is a step in generating it. Here is the pod file that was working before. I get the error described above when doing a "pod install".

[Podfile.zip](https://github.com/CocoaPods/Nanaimo/files/3127507/Podfile.zip)

**Comment by jpfortin** [comment]
I've copied the Pod into a new Xcode project, ran `pod install` and it worked fine. So, I'll close this ticket for now again. Thanks.
