### ISSUE TITLE
Saving a Cordova .pbxproj breaks

### ISSUE THREAD

**Issue by rocco** [CocoaPods/Nanaimo#8]
I use xcodeproj 1.4.0 (which uses Nanaimo since this version) in a fastlane setup to build a Cordova project. Parsing works after I manually fix the project.pbxproj (there some paths are missing " in the [Cordova template](https://github.com/apache/cordova-ios/blob/master/bin/templates/project/__TEMP__.xcodeproj/project.pbxproj) - lines 50 ff.)

However, writing the .pbxproj fails as follows. It's a bit hard to say if this is a bug in the .pbxproj or not, seems like an _empty_ object appears there and Nanaimo breaks:

```
/Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:63:in `write_object': [!] Cannot write  to an ascii plist (RuntimeError)
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `each'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:19:in `write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:55:in `write_object'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `each'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:19:in `write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:55:in `write_object'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:29:in `block (2 levels) in write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:28:in `each'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:28:in `block in write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:24:in `each'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:24:in `write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:55:in `write_object'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `each'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/xcode_project_writer.rb:19:in `write_dictionary'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:55:in `write_object'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:29:in `write'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `block in save'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `open'
    from /Users/Rocco/.rvm/gems/ruby-2.1.5/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `save'
    from Fastfile:93:in `block (2 levels) in parsing_binding'
```

Any idea if this is a Nanaimo issue or an error in the Cordova-generated .pbxproj file?

My fix for now is to use the xcodeproj gem in Version 1.3.2 which does not use Nanaimo - saves just fine.

**Comment by segiddins** [comment]
Please share steps to reproduce the issue, thanks!

**Comment by mmerickel** [comment]
I just ran into this issue because I was passing a `Pathname` object to a `target.arget.build_configuration_list.set_setting(k, v)`. It appears the `Writer#write_object` method is quite strict on what it accepts and may need to be relaxed.

**Comment by segiddins** [comment]
@mmerickel you should be setting it as a string

**Comment by mmerickel** [comment]
@segiddins It worked before upgrading.

**Comment by segiddins** [comment]
Sorry, you're right. Can you share a code snippet that reproduces the problem?

**Comment by mmerickel** [comment]
```ruby
#!/usr/bin/env ruby

require 'pathname'
require 'xcodeproj'

project_path = Pathname.new('DummyProject.xcodeproj')
plist_path = Pathname.new('DummyProject/Info.plist')

project = Xcodeproj::Project.new(project_path)

target = project.new_resources_bundle('DummyProjectBundle', :ios)
target.build_configuration_list.set_setting('INFOPLIST_FILE', plist_path)

project.save
```

produces the following stacktrace:

```
/Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:63:in `write_object': Cannot write DummyProject/Info.plist to an ascii plist (RuntimeError)
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:118:in `each'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:118:in `write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:19:in `write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:55:in`write_object'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:118:in `each'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:118:in `write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:19:in `write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:55:in`write_object'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:29:in `block (2 levels) in write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:28:in `each'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:28:in `block in write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:24:in `each'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:24:in `write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:55:in`write_object'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:118:in `each'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:118:in `write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/xcode_project_writer.rb:19:in `write_dictionary'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:55:in`write_object'
        from /Users/michael/.gem/ruby/2.0.0/gems/nanaimo-0.1.4/lib/nanaimo/writer.rb:29:in`write'
        from /Users/michael/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `block in save'
        from /Users/michael/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `open'
        from /Users/michael/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `save'
        from ./reproduce_8.rb:14:in `<main>'
```

**Comment by segiddins** [comment]
Thanks!
